### ISSUE TITLE
repo: mongodb

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#1]
##### Name of collection
mongodb

##### GitHub maintainers

@rhysmeister

**Comment by gundalow** [comment]
@rhysmeister repo has been created https://github.com/ansible-collections/mongodb
And you have maintainer powers on there.

Integration tests will fail at the moment, though we should be good to start allowing PRs to be created here.

**Comment by rhysmeister** [comment]
@gundalow Great stuff thanks for your efforts. Lots of complaints about syntax in the integration tests. Is this something I need to look at?

**Comment by gundalow** [comment]
@rhysmeister Ignore the integration tests for the moment. And it appears we don't have any unit tests, so I'll disable that.

**Comment by gundalow** [comment]
@rhysmeister I believe mongodb is all good (apart from publishing) so I'll close this issue. Please reopen if there is anything else
