### ISSUE TITLE
Ansible 2.10 collection notification issues

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/overview#102]
The only purpose of this issue is to collect all issues that have been created in collection repositories for announcing information on Ansible 2.10.

**Comment by bmillemathias** [comment]
for openstack -> https://storyboard.openstack.org/#!/story/2007982

**Comment by gundalow** [comment]
@felixfontein What do you think should be done with the open issues listed above?

**Comment by felixfontein** [comment]
@gundalow I closed the remaining open ones.
