### ISSUE TITLE
collection_requirements are unclear with dependencies and version_added

### ISSUE THREAD

**Issue by mdellweg** [ansible-collections/overview#106]
##### SUMMARY
In overview/collection_requirements.rst
the lines:
"dependencies MUST be set to '>=1.0.0' (Might have to think about dependency order when publishing)"
and
"Use collection version numbers for version_added (otherwise version_added_collection must be provided, but this is discouraged)"
are rather cryptic. Please elaborate on their scope and meaning.

Is it
"versioned dependencies on other collections MUST be specified using the '>=' operator (e.g. namespace.collection>=1.0.0)"
and
"the 'version_added' field must be present and and refer to the corresponding collection version (version_added_collection SHOULD not be used anymore)"

##### ISSUE TYPE
- Bug Report

**Comment by felixfontein** [comment]
I think the first means that you should always have versioned dependencies, and always require at least version 1.0.0 of a collection (and not accept 0.x.y releases).

The second means that when you use `version_added` for modules, plugins or options, the version numbers you put there must be versions of your collection, and not of random other things (like Ansible versions). If you refer to versions of other things, you need to specify `version_added_collection` as well. But you shouldn't do that anyway, so the use of `version_added_collection` is discouraged (it was never encouraged in the past either, so "anymore" doesn't make sense).

**Comment by felixfontein** [comment]
Can you check whether the clarifications in #107 make it easier to understand for you?
