### ISSUE TITLE
Request for a collaborator to be added

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/overview#114]
##### SUMMARY

Hello, I maintain the community.mongodb collection. I'd like to add @cognifloyd as a collaborator but can't seem to do it myself. Can anyone assist?

##### Name of collection
community.mongodb

**Comment by gundalow** [comment]
@cognifloyd welcome to the community. You'll need to accept via https://github.com/ansible-collections/community.mongodb/invitations which will give you `maintainer` powers, the same as @rhysmeister 

@rhysmeister nice to see the mongodb community growing :)

**Comment by rhysmeister** [comment]
Thanks for the quick response.
