### ISSUE TITLE
Slack integration for all ansible-collections Github repositories

### ISSUE THREAD

**Issue by piroux** [ansible-collections/overview#115]
##### SUMMARY

I would like to [receive slack notifications](https://github.com/integrations/slack) from events happening in each collection repo, but the slack integration has not been installed yet.
![Screenshot from 2020-09-23 08-56-32](https://user-images.githubusercontent.com/438492/93978705-a6892800-fd7c-11ea-9f8c-0a19115a1baf.png)

##### SOLUTION

Only an org owner can add it: https://github.com/apps/slack/installations/new

Given that it has to be installed at the org level, it could be be setup for all repositories in the `ansible-collections` github organization in one go:
![Screenshot from 2020-09-23 09-15-48](https://user-images.githubusercontent.com/438492/93979365-886ff780-fd7d-11ea-98ef-ae941f3b62f2.png)

##### ISSUE TYPE
- Repo Maintenance

**Comment by gundalow** [comment]
@piroux Seems like a good thing to do. I've enabled Slack for all of ansible-collections.

Does this work for you now?

**Comment by piroux** [comment]
Thanks for doing it !

However, it is still reporting that the slack integration is not installed for repos that I tried to subscribe to:
- `ansible-collections/community.general`
- `ansible-collections/ansible.posix`
With a messages to the Github App in Slack, like this one:
```
/github subscribe ansible-collections/community.general
```
I did not try the other repos of the `ansible-collections` Github org, but I guess it would be the same.

Note that I sucessfully receive events from `ansible/ansible` and many other repos from other orgs.

**Comment by gundalow** [comment]
Looks like the setting got reverted, could you please try again?

**Comment by piroux** [comment]
Now it is working :+1:

**Comment by piroux** [comment]
:information_source:  For future visitors here:

If you want to subscribe in Slack, only to the releases of an Ansible community Github repo, and not be notified for each commit, merge, issues and PR, ... etc, there is a [bug in the Git Slack app](https://github.com/integrations/slack/issues/1037) which makes this command irrelevant:
```
/github subscribe ansible-collections/community.general releases
```

So for each repo, the solution is to subscribe to every features, then to unsubscribe to all except the releases. For instance:
```
/github subscribe ansible-collections/community.general
/github unsubscribe ansible-collections/community.general issues, pulls, deployments, statuses, public, commits
```
