### ISSUE TITLE
Moving content from collections in Ansible 2.10 to collections currently outside, or: should we add new collections to 2.10.x?

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/overview#117]
To continue the discussion from today's [community meeting](https://github.com/ansible/community/issues/539#issuecomment-701599144).

**Comment by geerlingguy** [comment]
Philosophically, I'm opposed, as it will further expand Ansible's footprint, and even with redirections make it so canonical FQCN module names would be different in the same version of Ansible.

Pragmatically, I could maybe be convinced, but I'd still rather those kinds of changes be in more major-ish releases.

**Comment by felixfontein** [comment]
If we don't allow new collections in 2.10.x, that means that we cannot deprecate content that should be moved, and that means that the content will stay in the original collection for 2.11 (and will get deprecated from 2.11.0 if the new collection has been added to Ansible 2.11). That means that users manually have to switch to the new collection via FQCNs in 2.11, and only in 2.12 redirections will be active.

On the other hand, if we add these collections to 2.10.x, we can already deprecate the content in the old collection at that point of time, and remove it in 2.11.0 and thus add redirections already in 2.11.0.
