### ISSUE TITLE
Community messaging

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#12]
- [X] Write overview doc https://github.com/ansible-collections/overview/pull/3
- [X] Reddit https://www.reddit.com/r/ansible/comments/f6d4ut/community_update_on_ansible_collections/
- [X] Ansible Twitter https://twitter.com/the_gundalow/status/1230170710900977664
- [X] Partner email - Done
- [X] [Changes impacting Contributors](https://github.com/ansible/community/issues/346#issuecomment-588379820)
- [ ] Google Group: ansible-announce - Subset, in particular running from devel. link to ansible-project & Reddit
- [x] Google Group: ansible-project
- [ ] Google Group: ansible-devel
- [ ] Google Group: ansible-outreach
- [ ] Update Collections Blog?
- [ ] Twitter `Did you know that the @ansible devel branch is about to get a lot smaller` (wordsmith to be much scarier)

**Comment by cpitre** [comment]
I consider the early information provided here as beneficial in staying informed of the changes and the process involved.  Being a co-organizer to a couple of Ansible meetups, I'm looking forward to relaying what I learn here to future meetings and meetup boards.  Do we have a way to spread this info out to the other Ansible meetup co-organizers? Or is that already covered via the ansible-outreach channel?   Thanks!

**Comment by gundalow** [comment]
@cpitre Thank you for your message.
For meetup I think the main points would be:
* Collections are coming 
* The `devel` branch will be changing, so if you use that, consider the impact.
* mention the documentation we have. 

If there any *any* questions that you, or the meetup members have please let me know and I'll get the FAQ updated.

**Comment by gundalow** [comment]
@phips thoughts on Twitter `Did you know that the @ansible devel branch is about to get a lot smaller?` (wordsmith to be much scarier) and link to https://github.com/ansible-collections/overview/edit/master/README.rst

**Comment by gundalow** [comment]
Collections have been a thing for a while, so closing this.
