### ISSUE TITLE
repo: ibm_zos_autoops

### ISSUE THREAD

**Issue by ulrich-hild** [ansible-collections/overview#121]
SUMMARY
requesting a new repo for the IBM autoops collection (by System Automation and Netview Team)

Name of collection
ibm_zos_autoops

GitHub maintainers
ulrich-hild
lueddea

**Comment by gundalow** [comment]
Done: https://github.com/ansible-collections/ibm_zos_autoops

@ulrich-hild @lueddea Please accept invite https://github.com/ansible-collections/ibm_zos_autoops/invitations

Could I also suggest you both set a GitHub avatar
