### ISSUE TITLE
Consider if cookiecutter could be used for collection_template

### ISSUE THREAD

**Issue by dmsimard** [ansible-collections/overview#122]
We currently have a repository that is meant to be used as a template for new collections: https://github.com/ansible-collections/collection_template

This template can then be used when creating a new repository if you're a member of the ansible-collections organization:
![Screenshot from 2020-11-10 11-34-05](https://user-images.githubusercontent.com/1291204/98702659-aa7f0280-2348-11eb-9b35-e23f7441234d.png)

Otherwise, an end user without access to the template can fork it instead and then go from there but it's not really the same thing: it keeps the git history, a relationship with the fork upstream, etc.

Another approach that could be worth considering is to leverage [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/).
I've googled a bit and found the following examples of Ansible-related cookiecutter templates which can help understand how it works:
- https://github.com/ansible/molecule-cookiecutter
- https://github.com/iknite/cookiecutter-ansible-role

**Comment by gundalow** [comment]
From @webknjaz on IRC
> @gundalow: by the way, I have a Git-based config skeleton workflow idea in mind that would be perfect for things that cannot be automatically inherited from the `.github` but could still be managed in a centralized manner. One of my co-maintainers (@jaraco) uses a special repo with different common configs (https://github.com/jaraco/skeleton) and then periodically `git merge`s it into tens of projects.
> I was thinking about doing this with the template repo. The workflow would be to update that repo and than merge it into all the right places

**Comment by gundalow** [comment]
WIP PR https://github.com/ansible/ansible/pulls/Ompragash
