### ISSUE TITLE
Update community wiki pages

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#125]
Currently "The Community Wiki" https://github.com/ansible/community/wiki is out of date, in particular

* [ ] The links to issues & PRs currently point to ansible/ansible rather than the collection repos
  * [x] Some Working groups should link to multiple repos AWS -> ansible.aws & community.aws
  * [x] Example correct link `https://img.shields.io/github/issues/ansible-collections/community.aws.svg`
* [x] Github -> GitHub
* [x] Add repo(s) at the top of the Working Group pages to each of the collections
* [ ] Where there is a single repo, see if there is a "pinboard" issue, if not make a note
* [ ] Move the following [pinboard issues](https://github.com/ansible/community/labels/pinboard)
  * [x] grafana
  * [x] mongodb
  * [ ] ACI (in Cisco's repo)
  * [x] crypto
  * [x] Postgresql
  * [ ] Each of the above should be [pinned](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/pinning-an-issue-to-your-repository)
 * [ ] Old pinboard issues should be closed with a comment linking to the new issue
 * [ ] Wiki pages should link to the new pinboard issues via shields.io

**Comment by dericcrago** [comment]
regarding the moving of pinboard issues, do we want to _actually_ move ([transfer](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/transferring-an-issue-to-another-repository)) them or open a new pinboard issue and close the existing one with a comment pointing to the new pinboard issue? It does look like moving them via GitHub would handle notifying / redirecting for us, but there is a caveat that will likely preclude us from being able to do it (in most cases):

> You can only transfer issues between repositories owned by the same user or organization account. You can't transfer an issue from a private repository to a public repository.

**Comment by felixfontein** [comment]
Moving probably won't work because transfer is only possible inside a GH org, as you pointed out (it would definitely be the best solution though). Opening new issues, adding a redirect notice, closing the old one, and pinging members of the WG is probably the best approach.

**Comment by dericcrago** [comment]
I've spent some time looking into the pinboards and I'm not sure the best way to reconcile them. I think it would be great to have some amount of standardization and this might be a good time to do it, but it gets kind of messy with some of the working groups spanning multiple collections.

I don't think it makes sense to have a pinboard per collection, unless they *are* for the **collection** and not the **working group**. With that in mind, I could see either 1) leaving the pinboards in `ansible/community` since several of them span multiple repos and having some in `ansible/community` and others on the collection could potentially be confusing or 2) creating working group repos (similar to the meetup repos under `ansible-community`) for pinboards and wikis. What thoughts do you have @gundalow / @felixfontein ?

```
Pinboards to move (17):
ansible/community #207 - VMware community pinboard
ansible/community #208 - Windows community pinboard
ansible/community #421 - AIX community pinboard
ansible/community #422 - Solaris community pinboard
ansible/community #429 - HP-UX community pinboard
ansible/community #430 - BSD community pinboard
ansible/community #431 - GitLab community pinboard
ansible/community #432 - macOS community pinboard
ansible/community #435 - PostgreSQL community pinboard
ansible/community #437 - Newbie community pinboard
ansible/community #438 - Crypto community pinboard
ansible/community #440 - ACI community pinboard
ansible/community #442 - MongoDB community pinboard
ansible/community #447 - OpenStack community pinboard
ansible/community #448 - oVirt community pinboard
ansible/community #498 - Grafana Pinboard
ansible/community #515 - Kubernetes Pinboard

Pinboards to verify (2):
ansible-collections/community.crypto #24 - Crypto Pinboard
ansible-collections/community.mysql #12 - MySQL community pinboard

Repos without a Pinboard (74):
ansible-collections/amazon.aws
ansible-collections/ansible.netcommon
ansible-collections/ansible.network
ansible-collections/ansible.posix
ansible-collections/ansible.utils
ansible-collections/ansible.windows
ansible-collections/arista.eos
ansible-collections/azure
ansible-collections/checkpoint
ansible-collections/cisco.asa
ansible-collections/cisco.ios
ansible-collections/cisco.iosxr
ansible-collections/cisco.nxos
ansible-collections/cloud.common
ansible-collections/cloud.roles
ansible-collections/collection_template
ansible-collections/community.asa
ansible-collections/community.aws
ansible-collections/community.azure
ansible-collections/community.cassandra
ansible-collections/community.digitalocean
ansible-collections/community.docker
ansible-collections/community.es
ansible-collections/community.general
ansible-collections/community.google
ansible-collections/community.grafana
ansible-collections/community.hashi_vault
ansible-collections/community.hrobot
ansible-collections/community.internal_test_tools
ansible-collections/community.kubernetes
ansible-collections/community.kubevirt
ansible-collections/community.libvirt
ansible-collections/community.molecule
ansible-collections/community.mongodb
ansible-collections/community.network
ansible-collections/community.okd
ansible-collections/community.postgresql
ansible-collections/community.proxysql
ansible-collections/community.qradar
ansible-collections/community.rabbitmq
ansible-collections/community.routeros
ansible-collections/community.sops
ansible-collections/community.vmware
ansible-collections/community.windows
ansible-collections/community.yang
ansible-collections/community.zabbix
ansible-collections/dellemc.enterprise_sonic
ansible-collections/dellemc.os10
ansible-collections/dellemc.os6
ansible-collections/dellemc.os9
ansible-collections/frr.frr
ansible-collections/google.cloud
ansible-collections/hetzner.hcloud
ansible-collections/ibm_zos_cics
ansible-collections/ibm_zos_core
ansible-collections/ibm_zos_ims
ansible-collections/ibm_zos_sysauto
ansible-collections/ibm.qradar
ansible-collections/ibm.spectrum_virtualize
ansible-collections/junipernetworks.junos
ansible-collections/kubernetes.core
ansible-collections/mellanox.onyx
ansible-collections/netapp
ansible-collections/openvswitch.openvswitch
ansible-collections/overview
ansible-collections/pureport
ansible-collections/skydive
ansible-collections/splunk.enterprise_security
ansible-collections/splunk.es
ansible-collections/symantec.epm
ansible-collections/trendmicro.deepsec
ansible-collections/vmware_rest_code_generator
ansible-collections/vmware.vmware_rest
ansible-collections/vyos.vyos

Working groups currently in the Wiki (44?):
AIX
AWS
AWX
Azure
BSD
Cassandra
Cloud-and-VM
Community
Container
Contributor-Experience
Crypto
DigitalOcean
Diversity
Docker
Docs
Galaxy
GDrive
GitLab
Grafana
hcloud
HP-UX
IPA
JBoss
Linode
Lockdown
macOS
Molecule
MongoDB
Network
News
OpenStack
Outreach
oVirt
PostgreSQL
pylibssh
RelEng
Remote-Management
Security-Automation
Solaris
Testing
Virt
VMware
Windows
Zabbix
```

**Comment by felixfontein** [comment]
Sometimes collections and working groups more or less coincide, like for crypto and for docker. (Probably also the case for DigitalOcean, Grafana, MongoDB and PostgreSQL, and maybe some more.) There it makes sense to move the pinboard into the collection repo so everything's in one place.

**Comment by Andersson007** [comment]
https://github.com/ansible/community/issues/435#issuecomment-737843236

**Comment by dericcrago** [comment]
We've created `ansible/transfer-issues` which we can use to transfer issues between orgs.

1. transfer the issue to the `transfer-issues` repo
1. transfer the ownership of the `transfer-issues` repo from `ansible` to `ansible-collections`
1. transfer the issue to the appropriate `ansible-collections` repo

We moved the grafana and mongodb pinboards using this method.

**Comment by felixfontein** [comment]
@dericcrago ah, that's a really cool idea to move issues :)

Can you move the docker agenda/task list (https://github.com/ansible/community/issues/408) this way to the community.docker repo?

**Comment by dericcrago** [comment]
@felixfontein - yes, thank you for bringing it to my attention, I will add it to the list (as well as look for other agenda / task lists)

**Comment by Andersson007** [comment]
> ansible/transfer-issues

Is it a temporary short-term-living repository? If no, wouldn't it be good to describe the purpose of the repository and the mentioned workflow there (e.g. to create a README)?

**Comment by samccann** [comment]
Community wiki has been archived in favor of the forum.
