### ISSUE TITLE
Collections requirements lack standards for community/repo management

### ISSUE THREAD

**Issue by jillr** [ansible-collections/overview#126]
##### SUMMARY

This is related to https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst

I'm thinking things like requiring the existence of a contributor guide and/or readme, an issue tracker, maybe a CoC?

##### ISSUE TYPE
- Bug Report

**Comment by felixfontein** [comment]
IMO the absolute minimal requirements should be:
1. README.md (does galaxy actually require it?) with some basic info - like some of the sections in https://github.com/ansible-collections/collection_template/blob/main/README.md. This isn't really needed for the Ansible package, but every collection should have one with at least the most basic information.
2. Publicly available issue tracker (preferably GitHub, but can also be something else; should be something where issues can be created without having to buy an account).
3. Information on which kind of contributions are accepted (might also be none).
4. Release notes / changelog. Can also be something different than antsibull-changelog, but not having a changelog is not OK.

I don't mind having more requirements, but these are the four most important ones I think we should definitely require.

**Comment by jillr** [comment]
The verbiage in https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#changelogs does talk about changelogs and I feel like inclusion is implied but it doesn't explicitly state "must have a changelog".  +1 Making that verbiage clearer.

On 2 I personally don't have a preference where the issue tracker is so long as it's, as felixfontein noted, available without a paid level of account (Github, Launchpad, a Bugzilla instance, etc).

**Comment by jillr** [comment]
These items have been discussed, voted on, and approved in the community meeting.  Closing as resolved.

**Comment by gundalow** [comment]
@jillr @felixfontein Thank you for all the thought that went into this.
As discussed in 2020-12-09 IRC meeting this has been covered, remaining items are in 
https://github.com/ansible-collections/overview/pull/135/files
