### ISSUE TITLE
repo: jpmens

### ISSUE THREAD

**Issue by jpmens** [ansible-collections/overview#14]
##### Name of collection

`jpmens`

##### GitHub maintainers

jpmens

**Comment by gundalow** [comment]
Hi @jpmens Just to clarify (and I most likely need to update the issue template)
This is to request https://github.com/ansible-collections/jpmens which will be community.jpmens

I picture this being used for things like `community.grafana` 

I wonder if I've confused the matter, Galaxy namespaces can be requested via https://github.com/ansible/galaxy/issues/new/choose

Maybe this is the right place, what do you picture going in https://github.com/ansible-collections/jpmens?

**Comment by jpmens** [comment]
I wanted a name space so as to learn how to do it and thus be able to teach how to do it.

You tell me what I need please; the way I read the issue template here was that this would give me `ansible-dollections/jpmens`, so a namespace called `jpmens.`. If that’s not the case, what should I do?

**Comment by gundalow** [comment]
Cool, so I think you want
https://github.com/jpmens/foocollection
and jpmens as a namespace https://github.com/ansible/galaxy/issues/new/choose

**Comment by jpmens** [comment]
Thank you, @gundalow
