### ISSUE TITLE
repo: community.elastic

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/overview#144]
##### SUMMARY
I would like a repo for a bunch of elastic modules.

##### Name of collection
community.elastic

##### GitHub maintainers
rhysmeister

**Comment by dmsimard** [comment]
Hi @rhysmeister and thanks for the issue -- we can create the repo for you.

Would you prefer if it would be empty ? We can also initialize it from a template: https://github.com/ansible-collections/collection_template

**Comment by rhysmeister** [comment]
Hello David,

Empty is fine. 

Cheers,

Rhys

**Comment by dmsimard** [comment]
@rhysmeister https://github.com/ansible-collections/community.elastic was created and you should have received an invitation as a collaborator. Let us know if you have any questions !
