### ISSUE TITLE
Created new conda module for managing conda packages

### ISSUE THREAD

**Issue by patsevanton** [ansible-collections/overview#145]
##### SUMMARY
Created new conda module for managing conda packages

##### Name of collection
Conda

##### GitHub maintainers

May be based on https://github.com/UDST/ansible-conda

**Comment by patsevanton** [comment]
@jiffyclub @brianhelba  https://github.com/UDST/ansible-conda/issues/1
@lowks https://github.com/ansible/ansible-modules-core/pull/3780
@tmoschou https://github.com/ansible/ansible/pull/40455
@bbaassssiiee https://github.com/evandam/evandam.conda/issues/12

**Comment by gundalow** [comment]
@patsevanton Thank you for raising this.

Are you interested in maintaining a new Ansible Collection for conda?

Is anyone here from the Anaconda company? I'm wondering if this new collection should be created at:
https://github.com/ansible-collections/
https://github.com/conda/


Either way, we (Ansible Community Engineering Team) can help get it setup

**Comment by patsevanton** [comment]
I learn Ansible.. Need get more skill)

**Comment by lowks** [comment]
How can I help ?


[image: Low Kian Seong on about.me]

Low Kian Seong
about.me/lowkianseong
  <http://about.me/lowkianseong>

**Comment by bbaassssiiee** [comment]
This is the original source I believe https://github.com/UDST/ansible-conda/issues/1

**Comment by lowks** [comment]
Still no movement of this ?

**Comment by samccann** [comment]
Conda resources available on Galaxy - https://galaxy.ansible.com/ui/search/?keywords=conda
