### ISSUE TITLE
repo: IBM DS8000

### ISSUE THREAD

**Issue by matancarmeli7** [ansible-collections/overview#148]
##### SUMMARY

Hi,
I would like to add a new repo for IBM DS8000 Ansible modules.

##### Name of collection
ibm.ds8000

##### GitHub maintainers
matancarmeli7

**Comment by gundalow** [comment]
@matancarmeli7 Done https://github.com/ansible-collections/ibm.ds8000
I've populated the repo with the default set of files, which includes GitHub Actions for tests

**Comment by matancarmeli7** [comment]
thanks @gundalow, there is a way that I can add new members from my teeam that could contribute code? or only you can?

**Comment by gundalow** [comment]
I think I'll need to invite them. If you let me know their GitHub names I can do that.

**Comment by matancarmeli7** [comment]
roysahar-ibm
ArbelNathan
tikolsky
barakda
lisyukanna
oriyarde
erantzabari

Thanks!

**Comment by matancarmeli7** [comment]
Hi @gundalow,
if I will want to add more members in the feature, how could I do it? members that I didn't mention here

**Comment by gundalow** [comment]
@roysahar-ibm @ArbelNathan @tikolsky @barakda @lisyukanna @oriyarde @erantzabari 
1. Please accept the link to join `github.com/ansible-collections` so you will get access to the newly created repo by accepting: https://github.com/ansible-collections/ibm.ds8000/invitations
2. May I suggest that you also set a [GitHub profile picture](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/personalizing-your-profile)

@matancarmeli7 I've made you an `admin` Can you see if you can `Invite teams or people` via https://github.com/ansible-collections/ibm.ds8000/settings/access

**Comment by matancarmeli7** [comment]
thanks!

**Comment by gundalow** [comment]
1. @ArbelNathan @barakda @erantzabari @lisyukanna @oriyarde @tikolsky Hi, can you please accept the invite for the `ibm.ds8000` Ansible Collection repository via https://github.com/ansible-collections/ibm.ds8000/invitations Without this you will not have GitHub permissions to work within the repository.

2. May I suggest that you also set a [GitHub profile picture](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/personalizing-your-profile)

3.  @matancarmeli7 (and others) is there anything else I can do to help you get the collection setup?

**Comment by matancarmeli7** [comment]
@gundalow, we will start working on the `ibm.ds8000` Ansible collection, we didn't have the time yet but soon we will start, so for now we don't need help, but thanks anyway

**Comment by erantzabari** [comment]
Hi @gundalow ,
The invitation has been expired - could you please resend it? Sorry for the inconvenience.

**Comment by gundalow** [comment]
@erantzabari @ArbelNathan @barakda @lisyukanna I've refreshed the invitation, can you please accept via https://github.com/ansible-collections/ibm.ds8000/invitations I believe the link will expire after a week.

**Comment by gundalow** [comment]
I assume all is good here so closing. 
Feel free to add a comment if you need help with anything
