### ISSUE TITLE
repo: community.dns

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/overview#163]
##### SUMMARY
The collection should contain useful plugins and modules for doing some DNS-related things.

I have some plugins and modules in [felixfontein.tools](https://ansible.fontein.de/collections/felixfontein/tools/) and [felixfontein.hosttech_dns](https://ansible.fontein.de/collections/felixfontein/hosttech_dns/) I would like to donate (after some refactoring / rewriting for some of them).

Also, once / if this collection is included in Ansible, we could move some of the DNS modules and lookups from community.general there.

##### Name of collection
community.dns

##### GitHub maintainers
@felixfontein
more if there are interested parties :)

**Comment by gundalow** [comment]
https://github.com/ansible-collections/community.dns 
Thanks!
