### ISSUE TITLE
Add repository link to galaxy page for collection

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/overview#172]
##### SUMMARY

On the GitHub landing page for this collection, it would be nice if the repo metadata links at the top of the page (which are currently empty—no description or website) had a link to https://galaxy.ansible.com/community/general

I like to be able to bounce between Galaxy and the source repo, and right now I can only go from Galaxy to the source repo and not vice-versa.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

readme.md

##### ANSIBLE VERSION

N/A

**Comment by gundalow** [comment]
> Since this discussion is now pretty much off-topic to this collection (the original issue has been solved a long time ago), can we either close it or move it somewhere else?

Good call, transferred to `/overview` repo

**Comment by gundalow** [comment]
Existing repos have been updated.
Remaining worked tracked as 
* Created Updating ansible-galaxy collection init tracked as ansible/ansible#74684
* Have Zuul set this automatically for new repos ansible/project-config#827


Therefore closing this
