### ISSUE TITLE
The content in 'How can I fix bugs in Ansible 2.9?' in the README needs to be updated

### ISSUE THREAD

**Issue by unnecessary-username** [ansible-collections/overview#175]
##### SUMMARY

This is Tong He from Red Hat MPQE Entitlement QE Team.

I believe it has been at least a few months that for non security-related bugfixes and minor changes, those PRs are no longer accepted in https://github.com/ansible/ansible/ . After contacting @relrod via Google Chat last Friday, new non security-related bugfixes and minor changes PRs are also not reflected on Ansible 2.9 (both upstream and Red Hat downstream) for a long while. So in this case the content in 'How can I fix bugs in Ansible 2.9?' in the README needs to be updated.
https://github.com/ansible-collections/overview#q-how-can-i-fix-bugs-in-ansible-2-9

Besides, I think this sentence 'For new PRs please wait for the new Collections to be created. FIXME' **in** 'I'd like to submit a pull request to an existing Ansible module. How will I know where this module will live?' could also be removed at this time.
https://github.com/ansible-collections/overview#q-i-d-like-to-submit-a-pull-request-to-an-existing-ansible-module-how-will-i-know-where-this-module-will-live

##### ISSUE TYPE
- Bug Report

**Comment by felixfontein** [comment]
I created #176 to address this.
