### ISSUE TITLE
Integration tests in collections started failing

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/overview#179]
##### SUMMARY
(not sure ansible/ansible repo is appropriate for the issue as it relates to testing against collections)

@mattclay @s-hertel after changing 8.3 to 8.4 for devel as was said in https://github.com/ansible-collections/overview/issues/45#issuecomment-889538991 I'm getting the errors at least in 2 repos shortly after the container starts:
```
02:08 Failed to install packages. Sleeping before trying again...
02:20 Error: Problems in request:
02:20 missing groups or modules: python
02:20 Failed to install packages. Sleeping before trying again...
02:32 Error: Problems in request:
```
Also tests on OpenSUSE 15 py3, RHEL 7.8, RHEL 8.3 are failing 
https://github.com/ansible-collections/community.postgresql/pull/121
https://github.com/ansible-collections/community.libvirt/pull/85

**Comment by felixfontein** [comment]
Also happens in:
- community.crypto: https://dev.azure.com/ansible/community.crypto/_build/results?buildId=21357&view=logs&j=d1aa158d-5ccc-5965-4eff-6f265629e8a8&t=edb6356f-d6ba-58f3-0499-ad1dbc31fe9b
- community.docker: https://dev.azure.com/ansible/community.docker/_build/results?buildId=21356&view=logs&j=d1aa158d-5ccc-5965-4eff-6f265629e8a8&t=edb6356f-d6ba-58f3-0499-ad1dbc31fe9b https://dev.azure.com/ansible/community.docker/_build/results?buildId=21356&view=logs&j=fb5040f6-3d11-5f6f-ffda-dee5511df61b&t=8dffa136-2c35-5ac9-e569-080720904c23 https://dev.azure.com/ansible/community.docker/_build/results?buildId=21356&view=logs&j=f8080c43-554d-5f46-6733-1d0668d7c9ba&t=ec6e8091-9c6c-5aed-8cd5-83984b815824 https://dev.azure.com/ansible/community.docker/_build/results?buildId=21356&view=logs&j=8b28d296-7d79-5886-b1e3-7c07ade40695&t=f9dae36f-5c8c-5ed0-c8c9-65ba2117277c
- community.general: https://dev.azure.com/ansible/community.general/_build/results?buildId=21358&view=logs&j=d1aa158d-5ccc-5965-4eff-6f265629e8a8&t=edb6356f-d6ba-58f3-0499-ad1dbc31fe9b https://dev.azure.com/ansible/community.general/_build/results?buildId=21358&view=logs&j=fb5040f6-3d11-5f6f-ffda-dee5511df61b&t=8dffa136-2c35-5ac9-e569-080720904c23 https://dev.azure.com/ansible/community.general/_build/results?buildId=21358&view=logs&j=f8080c43-554d-5f46-6733-1d0668d7c9ba&t=ec6e8091-9c6c-5aed-8cd5-83984b815824

**Comment by saito-hideki** [comment]
Same here:
* ansible.posix: https://dev.azure.com/ansible/ansible.posix/_build/results?buildId=21412&view=logs&s=f1c67d30-e10f-5db0-113f-3b3828e65818&j=d1aa158d-5ccc-5965-4eff-6f265629e8a8
```
37:24 Error: Problems in request:
37:24 missing groups or modules: python
37:24 Failed to install packages. Sleeping before trying again...
```

**Comment by mattclay** [comment]
The issues with RHEL 8.4 should be resolved now, see: https://github.com/ansible-collections/overview/issues/45#issuecomment-889968084

The announcement about the RHEL 8.4 change was sent out before the PR adding support was merged.

**Comment by felixfontein** [comment]
I can confirm that, I just merged the community.docker PR (https://github.com/ansible-collections/community.docker/pull/185).

**Comment by Andersson007** [comment]
Thanks everyone!
