### ISSUE TITLE
Ansible community.kubernetes.k8s module

### ISSUE THREAD

**Issue by Sg-23** [ansible-collections/overview#180]
I am using community.kubernetes.k8s module for deploying my k8s templates but I'm getting the error
"msg": "'template' is only supported parameter for 'k8s' module."
According to ansible official documentation and example, template parameter is supported for community.kubernetes.k8s and not for k8s module.
Ansible version: 2.10.12

**Comment by felixfontein** [comment]
This is the wrong place to ask this question. You probably want to look here: https://docs.ansible.com/ansible/latest/user_guide/modules_support.html#support

The best places are the ansible-project mailing list (https://groups.google.com/g/ansible-project) or the #ansible Libera.chat channel.

Alternatively, the community.kubernetes (now kubernetes.core) collection repository might be useful as well: https://github.com/ansible-collections/kubernetes.core/
