### ISSUE TITLE
repo: community.sap

### ISSUE THREAD

**Issue by rainerleber** [ansible-collections/overview#188]
##### SUMMARY
Collection focusing on modules working and interacting with SAP systems. 

##### Name of collection
community.sap

##### GitHub maintainers

rainerleber
tbludau

**Comment by Andersson007** [comment]
@rainerleber hey, sorry for the late reply, was on PTO. We'll discuss this tomorrow and will get back to you, thank you!

**Comment by gundalow** [comment]
@rainerleber Hi, 
Their is some work already taking place in https://github.com/redhat-sap to make an Ansible Collection for SAP (they already have various SAP roles). I've let the maintainers know. I think it would be great if we could work on this together.

**Comment by rainerleber** [comment]
@gundalow Hi,
thank you for the reply.
yes i know them and i'am also in contact with Markus Koch. So i think i will close this issue.

**Comment by rhmk** [comment]
@rainerleber : Feel free to raise an issue and add the code to the infrasap project in the according collection

**Comment by Andersson007** [comment]
@rainerleber @tbludau hi, I've created https://github.com/ansible-collections/community.sap and have sent invites to you, please check your mailboxes. If everything is fine, feel free to close the issue. Thank you!

**Comment by rainerleber** [comment]
@Andersson007 I am not finding the collection on Galaxy. Could you have a look on it ?

**Comment by Andersson007** [comment]
@rainerleber yep, it won't work automatically.
1. I'll adjust Zuul configs (a tool that will publish the collection) maybe today or tomorrow.
2. When it's done I'll let you know and you will release the collection
3. Zuul seeing a release tag will publish the collection (provided that the tests are green)

**Comment by Andersson007** [comment]
@rainerleber I created the PRs ^ to adjust the configs but I don't have power to merge them myself.
Once they got merged (please check tomorrow, they should be merged), release the collection using [this guide](https://github.com/ansible/community-docs/blob/main/releasing_collections_without_release_branches.rst).
I suggest starting with `0.1.0`.
If everything is fine, Zuul will publish the collection on Galaxy.
If any questions, feel free to ask.

**Comment by rainerleber** [comment]
@Andersson007 thank you for the fast reaction and take care about :-)

**Comment by Andersson007** [comment]
@rainerleber you're welcome!

**Comment by gundalow** [comment]
> @rainerleber I created the PRs ^ to adjust the configs but I don't have power to merge them myself. Once they got merged (please check tomorrow, they should be merged), release the collection using [this guide](https://github.com/ansible/community-docs/blob/main/releasing_collections_without_release_branches.rst). I suggest starting with `0.1.0`. If everything is fine, Zuul will publish the collection on Galaxy. If any questions, feel free to ask.

@rainerleber The Zuul changes have been merged, so you should be able to git tag
