### ISSUE TITLE
namespace: vultr

### ISSUE THREAD

**Issue by resmo** [ansible-collections/overview#194]
##### SUMMARY

Not sure, if this was the right place, but I like to claim a galaxy namespace `vultr` for a collection hosted under gh/vultr (to be created). The collection is already in ansible community package but as ngine_io.vultr. 

The collection is transitioning to a v2 vultr api (once ready) and this will be a breaking change. We would like to keep ngine_io.vultr (and mark it deprecated) while adding the vultr.cloud collection. 

Thanks

##### Name of collection
vultr.cloud

##### GitHub maintainers
@ddymko
@resmo

**Comment by gundalow** [comment]
Once we've got the new collections setup, we can look at what's best to do regarding deprecating `ngine_io.vultr` and possibly including the new collection(s) in the `ansible` package.

**Comment by gundalow** [comment]
https://galaxy.ansible.com/vultr has been created and `resmo` set as owner.

We suggest adding other namespace owners. They will have needed to log into galaxy.ansible.com at least once to create their account.

We can organise deprecating other content via Chat.
