### ISSUE TITLE
repo: community.lbry Galaxy release problem,

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/overview#198]
##### SUMMARY

Hello, not sure where the right place for this request would be, but I have a problem with releasing to Galaxy on the following collection...

https://github.com/ansible-collections/community.lbry

I'm not entirely sure if the problem is on my side or not. I created a 0.1.0 release tag a week ago and I expect my release to appear at the following url: https://galaxy.ansible.com/community/lbry

Can anyone assist?

##### Name of collection
community.lbry

##### GitHub maintainers

rhysmeister

**Comment by Andersson007** [comment]
@rhysmeister hello, seems that the collection is not in zuul configs, I'll submit a PR to add it but i don't have permissions to merge things there, so it can be done tomorrow. I'll let you know when it is. Then you can re-tag and check.
I'll let you know

**Comment by rhysmeister** [comment]
@Andersson007, Great stuff, thank you.

**Comment by Andersson007** [comment]
@rhysmeister hi, the collection has been added to zuul configs, could you please re-tag your release and let us know if everything is fine or not?

**Comment by rhysmeister** [comment]
Boom it's there: https://galaxy.ansible.com/community/lbry

Thanks for your quick work once again!

Rhys

**Comment by Andersson007** [comment]
@rhysmeister thanks for the confirmation, you're always welcome!
