### ISSUE TITLE
repo: dellemc_networking.sonic

### ISSUE THREAD

**Issue by javeedf** [ansible-collections/overview#21]
##### SUMMARY

This shall be the Ansible collection repository for Dell EMC Networking SONiC

##### Name of collection
dellemc_networking.sonic

##### GitHub maintainers
https://github.com/skg-net
https://github.com/javeedf

**Comment by javeedf** [comment]
@gundalow  we are in the process of releasing this code. Could you please this repository?

It would help us release on time

**Comment by gundalow** [comment]
https://github.com/ansible-collections/dellemc_networking.sonic created

**Comment by gundalow** [comment]
Believe this is done. Please reopen if not
