### ISSUE TITLE
Project enablement for repositories in ansible-collections org

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/overview#210]
Hello, I looked around in discussions and issues but saw no other posts regarding the ask that repository owners be able to create projects of their own. 

When I go to the projects tab, the option to add a project in either classic or beta is not there, I don't know if this is something the org wants to limit or not, so I will ask and wait. 

[Here is a link to he project board for this org](https://github.com/orgs/ansible-collections/projects?query=is%3Aopen&type=classic).

**Comment by Andersson007** [comment]
@gundalow any ideas? (no need to reply now, we can wait until your PTO is over)

**Comment by ddimatos** [comment]
Thanks for giving this some consideration, it’s really going to be helpful to us in migrating all our issues to git and managing them transparently .

**Comment by gundalow** [comment]
@ddimatos I agree it would be good for you to be able to create your own GitHub Project boards. 
Which repository is this for, we can check the settings?

**Comment by ddimatos** [comment]
@gundalow - this would be great; it would be fore repositories [ibm_zos_core](https://github.com/ansible-collections/ibm_zos_core) and I am checking with Bryant on [IMS](https://github.com/ansible-collections/ibm_zos_ims)

**Comment by gundalow** [comment]
@ddimatos You have `admin` on ansible-collections/ibm_zos_core and Project Boards are available.

Do you see `Add Project` on https://github.com/ansible-collections/ibm_zos_core/projects?type=new

**Comment by ddimatos** [comment]
I do see the add, I have been able to its just the next step that does not work, let me share some screen shots
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/25803172/186205676-9a3fc723-6fa5-460f-bc42-70c9e21551db.png">
After I follow through the third highlighted box i sort of hit a dead end
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/25803172/186205854-15c1d90f-7abe-4978-8771-ea92716cb2e2.png">

**Comment by ddimatos** [comment]
@gundalow - adding some more context to this; I have been able to see `Add Project` but the only projects I can add are ones that have been created in the `ansible-collections organization` , so when I go to the `ansible-collections organization` I don't  get the `New Project` button, that is where we fall short in the flow.

**Comment by gundalow** [comment]
Strange, maybe you need permissions on the whole org.

If created https://github.com/orgs/ansible-collections/projects/10/

**Comment by ddimatos** [comment]
This works (having created it for me) , could I bother when ever time permits, if you could do the same for repository `ibm_zos_ims`

**Comment by ddimatos** [comment]
Thank you, marking this as resolved, GH projects is working out great for us, thank you.
