### ISSUE TITLE
community.elastic collection missing from Zuul configs

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/overview#222]
##### SUMMARY

Hello, I'm not able to publish this collection to Galaxy. It seems to be missing from the Zuul configs...

https://github.com/ansible/zuul-config/blob/7a0096c13155402a94f5943940a5be801a948bdb/resources/ansible.yaml

Could someone take a look please?

##### ISSUE TYPE
- Bug Report

**Comment by Andersson007** [comment]
@rhysmeister hello, i'll let you know when the PRs i created to add the collection are merged

**Comment by Andersson007** [comment]
fyi there are some technical issues on Zuul's side, we're working on this, i'll let you know when it's solved

**Comment by rhysmeister** [comment]
Great stuff. Thank you.
