### ISSUE TITLE
Wrong PyPI reference URL to the ansible-core package

### ISSUE THREAD

**Issue by eskultety** [ansible-collections/overview#228]
##### SUMMARY

https://pypi.org/project/ansible/ mentions the `ansible-core` package in the following paragraph:

> This is the ansible community package. The ansible python package contains a set of independent Ansible collections that are curated by the community, and it pulls in [ansible-core](https://pypi.org/project/ansible/pypi.org/project/ansible-core/).

 The actual link points to https://pypi.org/project/ansible/pypi.org/project/ansible-core/ instead of https://pypi.org/project/ansible-core.

##### ISSUE TYPE
- Bug Report

**Comment by eskultety** [comment]
There are so many ansible repos out there I didn't manage to find the one actually responsible for the PyPI releases. If this is not the right place please point me to the right place.

**Comment by felixfontein** [comment]
The right one would be github.com/ansible-community/antsibull; since it's a different GH org I cannot simply move the issue there, but I'll create a fix there to fix this :)

**Comment by felixfontein** [comment]
https://github.com/ansible-community/antsibull/pull/541 fixes this.
