### ISSUE TITLE
Python requirements for collections

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/overview#230]
##### SUMMARY
[ansible-inclusion](https://github.com/ansible-collections/ansible-inclusion/tree/main) links to the Collections Checklist:

https://github.com/ansible-collections/ansible-inclusion/blob/9c5c47ea525e162537069c70dce880906da17a6d/README.md?plain=1#L66-L71

But this checklist requires Python 2.6 or greater and Python 3.5 or greater support:

https://github.com/ansible-collections/overview/blob/main/collection_checklist.md?plain=1#L26

 However, Ansible 9 is based on ansible-core 2.16 which [doesn't support Python 2.6 or 3.5](https://docs.ansible.com/ansible/9/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix). Should we update the requirements, or are there any (good) reasons to keep it as-is?

##### ISSUE TYPE
- Bug Report

**Comment by felixfontein** [comment]
I guess we forgot to update the checklist when we updated the [actual requirements](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#python-requirements) earlier this year.

I've created a PR to update the checklist: https://github.com/ansible-collections/overview/pull/231

**Comment by mariolenz** [comment]
resolved_by #231

Thanks @felixfontein!
