### ISSUE TITLE
Issue Mover

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#25]
We need some nicer to allow movement of issues from gh/ansible/ansible to gh/ansible-collections/REPO.

Built in GitHub functionality only allows Issues to be moved within the same GH Org.

PR mover is solved by https://github.com/ansible-collections/overview/issues/5

I've contacted GitHub to see if they have any ideas

- [ ] Add `migrated_to_collection_repo` https://github.com/ansible/ansible/labels/migrated_to_collection_repo to moved items.

**Comment by jamescassell** [comment]
Would it be a reasonable workaround to temporarily move the relevant repo into ansible/ org, move the issue, then move the repo back?

**Comment by jillr** [comment]
Did we get any response from Github? I've heard that there may exist a bot that helps issue submitters move their own issues, is that a possibility?
