### ISSUE TITLE
Docs to use FQCN?

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#29]
We need to confirm, though the thought is that we should update documentation to use FQCN.

Module & plugin docs
Examples repos
Training materials

**Comment by samccann** [comment]
This should also likely apply to the examples used within the .rst docs. I plan on starting that for the networking stuff, unless I hear otherwise.

**Comment by gundalow** [comment]
Modules added only in collection (ie never in devel) MUST have FQCN in `EXAMPLES`

**Comment by geerlingguy** [comment]
Closing as duplicate of #40
