### ISSUE TITLE
repo: community.zabbix

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/overview#34]
##### SUMMARY
(Official)? Zabbix module namespace by community for the:
https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/monitoring/zabbix 

Near future plans would be to deploy custom CI so we can test modules against every zabbix LTS release.

https://www.zabbix.com/life_cycle_and_release_policy

##### Name of collection
community.zabbix

##### GitHub maintainers
@D3DeFi
@sky-joker

**Comment by gundalow** [comment]
Please accept invite https://github.com/ansible-collections/community.zabbix/invitations


Repo: https://github.com/ansible-collections/community.zabbix

https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration
When moving the files from community.general you may need to `s/community.general/community.zabbix/g` as well

**Comment by gundalow** [comment]
See https://github.com/ansible-collections/grafana/blob/master/.github/workflows/ansible-test.yml#L55-L62 for how Grafana are testing against multiple Grafan versions.

Note in this case you can't use ansible-test's `--docker` are you will end up with machines on non-routable networks.

**Comment by D3DeFi** [comment]
Removal commit from `community.general` [here](https://github.com/ansible-collections/community.general/pull/11).
Adjustements to `ansible/ansible:temp-2.10-devel` [here](https://github.com/ansible/ansible/pull/68190).

**Comment by gundalow** [comment]
I believe all of this is complete, it not, please reopen

**Comment by D3DeFi** [comment]
Just a quick question tho, will currently open PRs/issues be moved to collection automatically or should I iterate through them and encourage users to reopen them in collection repo?
