### ISSUE TITLE
repo: IBM Spectrum Virtualize

### ISSUE THREAD

**Issue by wangpww** [ansible-collections/overview#36]
##### Name of collection
I want to use "IBM Spectrum Virtualize" as my repo name, but in my galaxy.yaml, the collection name is "spectrum_virtualize"

##### GitHub maintainers
wangpww

**Comment by wangpww** [comment]
@thedobul3j please help to review it.

**Comment by gundalow** [comment]
Hi,
Just to clarify.
Galaxy uses he collection name and namespace from `galaxy.yml`.
Galaxy doesn't use to GitHub repo name at all. 

So as long as your `galaxy.yml` has `spectrum_virtualize`, you are good.

**Comment by wangpww** [comment]
@gundalow Thank you for your clarification. Please help to create the repo and add access right for me, thank you very much.

**Comment by gundalow** [comment]
https://github.com/ansible-collections/ibm.spectrum_virtualize (we are using namespace`.`collection_name)

Please accept the invite via https://github.com/ansible-collections/ibm.spectrum_virtualize/invitations

**Comment by wangpww** [comment]
@gundalow I don't know the repo is ok or not since in your invite link: https://github.com/ansible-collections/ibm.spectrum_virtualize/invitations, I need to enable two-factor authentication, but I failed to do it since all the app I can not download from china and by using SMS is not support china now.

**Comment by gundalow** [comment]
> @gundalow I don't know the repo is ok or not since in your invite link: https://github.com/ansible-collections/ibm.spectrum_virtualize/invitations, I need to enable two-factor authentication, but I failed to do it since all the app I can not download from china and by using SMS is not support china now.

@wangpww I believe you can use any standard 2FA application for your phone.

From a quick Google it looks like you can manually modify the html page so you can enter your mobile number: https://gist.github.com/xcatliu/4e1d5e69fc5f8a49e4e6

Once you've setup via SMS you can add a security key, see https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication

**Comment by wangpww** [comment]
@gundalow So the 2FA must be enabled?

**Comment by gundalow** [comment]
> @gundalow So the 2FA must be enabled?

This is correct. 
GitHub 2FA is set at the GitHub Organization level (https://github.com/ansible-collections) rather than the repo level.

**Comment by wangpww** [comment]
@gundalow I am trying the method you sent to me, but it not works now, since it may releated to the telecom operators(some comments in the link), my phone can not receive the SMS
what's the impact to me if I can not enable the 2FA

**Comment by gundalow** [comment]
@wangpww can you use a 2FA App, rather than SMS? For example I use https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2

Do you have any other colleges in China that use GitHub you could speak to see if they've got it setup?

If you don't have 2FA enabled you will not have direct commit to the repo.

**Comment by resmo** [comment]
I can recommend authy (https://play.google.com/store/apps/details?id=com.authy.authy) it has a desktop app (and chromium app) and does backup and sync (on clients).

**Comment by wangpww** [comment]
@gundalow I enabled it with the SMS by following your google link, thank you very much.
@resmo Thank you.

**Comment by gundalow** [comment]
@wangpww Is there anything left to do here, or can we close this issue?

**Comment by wangpww** [comment]
Yes, we can close it. Thank you very much for your help.
