### ISSUE TITLE
repo: scaleway

### ISSUE THREAD

**Issue by remyleone** [ansible-collections/overview#38]
##### Name of collection

`scaleway`

##### GitHub maintainers

@scaleway/devtools

If assigning team does not work, you can use the individual GitHub profile:

@remyleone
@jerome-quere 
@kindermoumoute
@QuentinBrosse 
@loicbourgois

**Comment by gundalow** [comment]
Hi @remyleone 
I see https://galaxy.ansible.com/scaleway has been created.
Is there anything else you need, if not could you please close this issue.
