### ISSUE TITLE
[1d] Remove `tests/sanity/requirements.txt` from collections

### ISSUE THREAD

**Issue by mattclay** [ansible-collections/overview#43]
Some collections have a `tests/sanity/requirements.txt` file copied from the ansible/ansible repo.

This file is not used by `ansible-test` and should be removed to avoid confusion. I've seen it in two collections, but others which copied these may also have it:

* community.general
* community.zabbix

### Call to action

* Please review your collections for this file and remove it if present. In the PR please reference this issue, so we can track where the fix has been applied.

**Comment by felixfontein** [comment]
That file also exists in community.crypto and community.network. I guess it was created by the migration script?

**Comment by Andersson007** [comment]
@mattclay @gundalow done, the issue can be closed

**Comment by gundalow** [comment]
Great work, thanks @Andersson007 this simplifies the repos and reduces confusion.

**Comment by Andersson007** [comment]
@gundalow thanks you and everybody who helped to cope with it:)
