### ISSUE TITLE
How to set the develop branch as the default branch for my repo

### ISSUE THREAD

**Issue by wangpww** [ansible-collections/overview#46]
##### SUMMARY

Hi admin,

My repo is https://github.com/ansible-collections/ibm.spectrum_virtualize
In the setting button, I didn't find any setting can be used to set the default branch, would you please help to guide me to do it? Thank you very much.

##### ISSUE TYPE
- Bug Report

**Comment by gundalow** [comment]
@wangpww Your default branch is `master` which is the same as the other collections.

Is there a reason you'd like to change it?

**Comment by gundalow** [comment]
I believe this is sorted, if not please re-open
