### ISSUE TITLE
[3d] Migrated Modules Messaging

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible-collections/overview#48]
##### SUMMARY

It is not entirely clear where modules have moved to, while a google search may clear up some things it is still hard to see which collection a module has moved to. 

I am proposing some documentation to list out where the modules have gone. I think a single page with the relevant information will go a long way.

| Module | Galaxy Name | Collection | Repo |
| -------  | ------------- | ---------- | ----- |
| ios_*.     | cisco.ios | https://galaxy.ansible.com/cisco/ios | https://github.com/ansible-collections/cisco.ios/ |
| digital_ocean_* |  community.general | https://galaxy.ansible.com/community/general | https://github.com/ansible-collections/community.general |

Less of a bug, and more of a feature, but there was not ability to create a feature. 

##### ISSUE TYPE
- Bug Report

**Comment by abenokraitis** [comment]
What you are suggesting I'm building for certified and supported Ansible content (as well as a contributors guide), but this wouldn't cover all community content unfortunately and would be a gap.

**Comment by felixfontein** [comment]
AFAIK the new docs generation for ACD will cover / contain this. Right now, there's https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml and https://github.com/ansible/ansible/blob/devel/lib/ansible/config/routing.yml (which are not always 100% up to date though).

**Comment by gundalow** [comment]
I'm aware of the following scripts to find where modules have moved to

1. https://github.com/AlanCoding/ansible-locate
2. https://gist.github.com/sivel/73a071faa7b37a851437a026aa94f7da
3. https://gist.github.com/cidrblock/40a540c54abb6f8767f7da7a85c84a94
4. https://github.com/ansible/ansibullbot/pull/1319

**Comment by gundalow** [comment]
@itdependsnetworks Thanks for raising this Ken, where would you expect to see this documented/linked from?

**Comment by itdependsnetworks** [comment]
Anywhere is fine tbh, I can at least note it and refer to on slack as an example

**Comment by abenokraitis** [comment]
Might be worthwhile to just take [https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml), parse it, and make it more readable at every Ansible release...

**Comment by itdependsnetworks** [comment]
Who is that directed at?

**Comment by abenokraitis** [comment]
@gundalow  is this a deliverable via the Distro or from Base?

**Comment by acozine** [comment]
Related to #67484

**Comment by samccann** [comment]
When a user searches google for ios_config for example, it will redirect to this collection-level page, which tells the user which collection it comes from and how to install the collection - https://docs.ansible.com/ansible/2.10/collections/cisco/ios/ios_config_module.html#ansible-collections-cisco-ios-ios-config-module

That will happen once the redirects are in place on the docsite (by Ansible 2.10 release).

**Comment by acozine** [comment]
Also related to https://github.com/ansible/ansible/issues/70267 and https://github.com/ansible/ansible/issues/67621
