### ISSUE TITLE
Docs updates (personas master List)

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#49]
##### SUMMARY

It's hopefully easier to track what improvements to the documentation are needed if we break it down by who, then secondly what.

Once we have an understanding of what needs doing we can link to specific PRs from here.

We may move content from https://github.com/ansible-collections/overview/blob/master/README.rst into the main doc site (though we must keep the sections in `README.rst` as we have given those links out)
### Persona: User

* Installing and using
  * Using Collections alongside ansible-base
  * Updating to a newer version of a Collection

### Persona: Contributor

* Where has my code gone (that was in a/a)
* What do I do with my a/a issues and PRs
* I want to contribute to a collection, how can I help
  * FIXME: list of ways they can help (review, docs, etc)
* How can I download and test a PR

### Persona: Collection Owner

* How to setup CI
* 

##### ISSUE TYPE
- Bug Report

**Comment by samccann** [comment]
This docsite was recommended as a good model to consider - https://www.rdoproject.org/contribute/

**Comment by samccann** [comment]
Personas and journeys for Ansible documentation are at https://github.com/ansible/docsite/tree/main/data/journeys
