### ISSUE TITLE
Update collection tests from RHEL 8.1 to 8.2

### ISSUE THREAD

**Issue by relrod** [ansible-collections/overview#54]
Collections which are tested on Shippable against RHEL 8.1 should update to RHEL 8.2.

This requires an update to shippable.yml to replace T=rhel/8.1 with T=rhel/8.2. Here's one such line in ansible/ansible:

https://github.com/ansible/ansible/commit/1c5c89baa6b082bb5769b0cda8cbca367ba6877a#diff-033d042b39454e8e066ab38fd89610a5L33-R33

Some tests may need to be updated. 

### Call to action

* If your collection uses Shippable for CI please update shippable.yml as detailed above. In the PR please reference this issue, so we can track where the fix has been applied.

**Comment by gundalow** [comment]
I believe this was completed last year.
