### ISSUE TITLE
[3w] Ansible test cases (2.9 -> 2.10 without user impact)

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#55]
### SUMMARY

One of the primary design goals of Ansible 2.10 is that Ansible 2.9 Playbook should work without modification, to ensure that's the case we need to define some test cases

#### Playbooks

- [ ] OpenStack installer
- [ ] Ansible Tower installer
- [ ] debops
- [ ] https://github.com/ansible/ansible-examples
- [ ] https://github.com/ansible/workshops

#### Specific tests
 
- [ ] Plugin Types
  - [ ] become
  - [ ] cache
  - [ ] callback
  - [ ] cliconf
  - [ ] connection
  - [ ] httpapi
  - [ ] inventory
  - [ ] lookup
  - [ ] netconf
  - [ ] shell
  - [ ] module
  - [ ] strategy
  - [ ] vars
- [ ] Commands
  - [ ] ansible
  - [ ] ansible-playbook
  - [ ] ansible-doc

**Comment by geerlingguy** [comment]
FYI I created a repo that is using GitHub Actions to test the same playbook running against 2.9.x stable and the 2.10.0 pre-release: https://github.com/geerlingguy/ansible-content-testing

The test runs are here: https://github.com/geerlingguy/ansible-content-testing/actions (it runs tests against stable, pre-release, and current devel (with allowed failure) every night)

It's currently testing:

  - collection from galaxy
  - role from galaxy
  - local standalone role
  - module from collection from galaxy
  - module from 2.9 that's been migrated to a collection in galaxy but is in 2.10 with mapping
  - plugin local to playbook (test plugin for jinja2)

If we wanted to add more plugin types to it, that would be fine with me (or just use it as a base for other types of tests).

**Comment by gundalow** [comment]
I believe this is all good as people have been using collections for some time.
