### ISSUE TITLE
Document deprecation process

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#58]
##### SUMMARY

Now that https://github.com/ansible/ansible/pull/68646 has been merged we need to view and possibly correct how they are defined.

* Collections don't use a leading `_` for deprecation, they use
routing.yml instead

When raising PRs to fix this, please mention https://github.com/ansible-collections/overview/issues/58 in the PR, so we can track where this has been fixed

- [x] community.general
- [x] community.network 

##### ISSUE TYPE
- Bug Report

**Comment by gregdek** [comment]
I'm going to assume that when we said "deprecations: Docs, ansible-test, update all collections" in a note that I converted to a ticket in #69 would have been covered here, so I closed #69 as a duplicate. If there's anything more we need to do with deprecations, let's track it here.

**Comment by gundalow** [comment]
Covered in https://docs.ansible.com/ansible/devel/dev_guide/module_lifecycle.html
