### ISSUE TITLE
Update collection tests from Fedora 30 to 32

### ISSUE THREAD

**Issue by relrod** [ansible-collections/overview#59]
Collections which are tested on Shippable against Fedora 30 should now test against Fedora 32 (so they are testing on 31 and 32), and at their discretion, drop support for Fedora 30 which is going end-of-life soon.

This requires an update to shippable.yml to add `T=linux/fedora/32`. Here's one such line in ansible/ansible:

https://github.com/ansible/ansible/commit/de59b17c7f69d5cfb72479b71776cc8b97e29a6b#diff-033d042b39454e8e066ab38fd89610a5R40

Some tests may need to be updated. 

### Call to action

* If your collection uses Shippable for CI please update shippable.yml as detailed above. In the PR please reference this issue, so we can track where the fix has been applied.

**Comment by relrod** [comment]
Refs https://github.com/ansible/ansible/pull/69222
Refs https://github.com/ansible/ansible/issues/69230

**Comment by gundalow** [comment]
Believe this was completed last year
