### ISSUE TITLE
Infra for maintainers of collections which are part of ansible-2.10+

### ISSUE THREAD

**Issue by gregdek** [ansible-collections/overview#60]
* Create a list of contact information for all collection owners.
* Create a mailing list for all collection owners.

This infra should include both people who are maintaining what's in ansible-2.10+ and people who *want to* maintain collections in 2.10+

**Comment by gundalow** [comment]
Also list of which use Shippable would be good.
We could use nested GitHub Team 
Ie team_shippable includes elders,team_cryto, etc

**Comment by Andersson007** [comment]
The repo is getting archived, closing, thanks everyone!
