### ISSUE TITLE
https://ansible.sivel.net/pr/byfile.html for community.general (move to eng.ansible.com?)

### ISSUE THREAD

**Issue by gregdek** [ansible-collections/overview#61]
Yep, this has been a useful tool and people rely upon it.

**Comment by felixfontein** [comment]
I guess it would also be useful for `community.network`, the other mass collection.

**Comment by gundalow** [comment]
It's been year and we still don't have this. Does anyone care?

**Comment by felixfontein** [comment]
I think we can close this.
