### ISSUE TITLE
repo: rabbitmq

### ISSUE THREAD

**Issue by odyssey4me** [ansible-collections/overview#7]
##### Name of collection
rabbitmq

##### GitHub maintainers
@chrishoffman @h-matsuo @jgkirschbaum @manuel-sousa @retr0h

**Comment by gundalow** [comment]
https://github.com/ansible-collections/rabbitmq has been created and I've given you `maintainer` powers`

**Comment by gundalow** [comment]
I'll leave this open till you confirm you are good.
Please update https://github.com/ansible-community/collection_migration/blob/master/scenarios/nwo/community.yml to add in a `rabbitmq:` entry

**Comment by gundalow** [comment]
ah, looks like the scenario didn't get updated, so need to move this modules from `community.general` into `community.rabbitmq` by following https://github.com/ansible-collections/overview/blob/master/README.rst#q-what-should-i-do-to-move-plugins-across-collections-during-migration

**Comment by odyssey4me** [comment]
@gundalow Apologies - I'm still catching up to this. What's the deadline for the move to be done?

**Comment by gundalow** [comment]
If the delete from `community.general` could be done within the next week that would be good. I haven't published `community.general` yet and would like to avoid them moving after that.

**Comment by gundalow** [comment]
@odyssey4me Hi, I assume this is all done so I'll close. If not please reopen.
