### ISSUE TITLE
Resolution of duplicate entries in BOTMETA

### ISSUE THREAD

**Issue by gregdek** [ansible-collections/overview#78]
https://github.com/ansible-community/collection_migration/issues/128

https://github.com/ansible-community/collection_migration/issues/201
I've talked with mkrizek and he's agreed to look at fixing this
(The problem with current fix is that it leaves entries which are directories with migrated_to fields)

**Comment by gundalow** [comment]
@abadger I think we can close this, what do you think?

**Comment by abadger** [comment]
Yes, i think so

**Comment by gregdek** [comment]
Thanks, closing.
