### ISSUE TITLE
repo: libvirt

### ISSUE THREAD

**Issue by odyssey4me** [ansible-collections/overview#8]
##### Name of collection
libvirt

##### GitHub maintainers
@joshainglis @karmab @drybjed @odyssey4me

**Comment by gundalow** [comment]
1) Please accept the invitation to join this repo https://github.com/ansible-collections/libvirt/invitations

2) Please update https://github.com/ansible-community/collection_migration/blob/master/scenarios/nwo/community.yml to add in a `libvirt:` entry

**Comment by odyssey4me** [comment]
@gundalow Apologies - I'm still catching up to this. What's the deadline for the move to be done?

**Comment by gundalow** [comment]
If the delete from `community.general` could be done within the next week that would be good. I haven't published `community.general` yet and would like to avoid them moving after that.

**Comment by gundalow** [comment]
@odyssey4me Hi, I assume this is all done, if not please re-open
