### ISSUE TITLE
Bot to support collections

### ISSUE THREAD

**Issue by gregdek** [ansible-collections/overview#81]
Tracking the following PR: https://github.com/gundalow/ansibullbot/pull/7

- [x] COLLECTION OWNER: Ensure `.github/BOTMETA.yml` is correct for each repo
- [ ] COLLECTION OWNER: Copy Directory level labels from c.general to each repos `.github/BOTMETA.yml` (each directory under `plugins/`) https://github.com/ansible-collections/community.general/commit/c006eb8a5f2709fc35aab686065e1b2d09d88bcb#diff-5baefb0f9c8093094911cec657444e70 etc
- [ ] Use a bot to ensure GitHub labels are consistent
- [ ] AWS instance per Bot

## Collections

- [X] community.general
- [ ] community.network
- [ ] community.aws
- [ ] amazon.aws

**Comment by jillr** [comment]
@gundalow I need to make some BOTMETA.yml changes first but I'm working on those and would like to plan to have ansibot deployed in https://github.com/ansible-collections/amazon.aws and https://github.com/ansible-collections/community.aws. Thanks!

**Comment by gundalow** [comment]
@jillr I've created the labels in two repos

**Comment by gundalow** [comment]
Moved to https://github.com/ansible-community/collection_bot/issues/15 since we now have a dedicated bot repo
