### ISSUE TITLE
repo: community.sops

### ISSUE THREAD

**Issue by endorama** [ansible-collections/overview#85]
##### SUMMARY

As suggested from https://github.com/ansible/ansible/pull/59641, a `sops` collection may be effective in providing a home for the `sops` related plugins (lookup and vars) currently on the route to be included in `community.general`.

##### Name of collection

`community.sops`

##### GitHub maintainers

@endorama

**Comment by gundalow** [comment]
@endorama Excellent, thank you. I'll do this shortly.

Do you know if anyone else would like to join you in being a maintainer?

**Comment by felixfontein** [comment]
I'm not a sops user, but I can help with setting the infrastructure up and reviewing.

**Comment by endorama** [comment]
@gundalow I asked in the sops-related issues if someone else is interested. As far as I know at the moment I'm the only one.

Thanks @felixfontein, your help is surely appreciated!

**Comment by gundalow** [comment]
It lives https://github.com/ansible-collections/community.sops

@endorama Please accept the invite via https://github.com/ansible-collections/community.sops/invitations

I've added a templated GitHub Actions workflow which will need tweaking depending on if there are any integration or unit tests https://github.com/ansible-collections/community.sops/blob/master/.github/workflows/ansible-test.yml



> @gundalow I asked in the sops-related issues if someone else is interested. As far as I know at the moment I'm the only one.

@endorama That's fine, just want to make sure you have support from day one. It's easy to add others.

@felixfontein Thanks for your help :)

**Comment by felixfontein** [comment]
@endorama I'll take a look at moving the existing plugin somewhen later today.
