### ISSUE TITLE
Changelog/Porting Guide requirements for collections within Ansible-2.10 (acd)

### ISSUE THREAD

**Issue by samccann** [ansible-collections/overview#88]
##### SUMMARY

We need to list out what collections need to have in place so that the Ansible 2.10 changelog and porting guides can generate correctly.

##### ISSUE TYPE
- Documentation

**Comment by samccann** [comment]
The goal here is to have a list of action items that the collection maintainers can implement so that their collections show up with appropriate information or links in the Ansible-2.10 changelog and Porting Guide.

I think this lists those collections: https://github.com/ansible-community/ansible-build-data/blob/main/2.10/acd.in

**Comment by felixfontein** [comment]
I think we need:
1. If possible, collections should use antsibull-changelog, or somehow else provide a changelogs/changelog.yaml file.
2. If that's not possible, we would like to have a URL for the changelog (and porting guide?) we can link to.

**Comment by felixfontein** [comment]
* Should subscribe to the issue https://github.com/ansible-collections/overview/issues/45
* Make sure `ansible-test sanity` is run (with at least the ansible-test from stable-2.10).

**Comment by samccann** [comment]
Should also conform to https://github.com/ansible-collections/overview/pull/90/files

**Comment by felixfontein** [comment]
If they want to self-publish the changelog and not provide changelogs/changelog.yaml (produced by antsibull-changelog or created by other means), they should create an issue in https://github.com/ansible-community/ansible-build-data/ and provide the changelog URL there.

**Comment by felixfontein** [comment]
Closing this since it has been implemented and announced.
