### ISSUE TITLE
repo: ciena.saos6

### ISSUE THREAD

**Issue by jgroom33** [ansible-collections/overview#91]
##### Name of collection
ciena.saos6

##### GitHub maintainers

jgroom33

**Comment by gundalow** [comment]
Hi, 
Thank you for this request

1) Is this to host https://github.com/ciena/ciena.saos6
2) Do you have have any links to ciena? 
3) Do you know anyone else that would be interested in being a maintainer?

**Comment by gundalow** [comment]
I missed that https://github.com/ciena/ciena.saos6 is under ciena's GitHub Organizations.
You could continue to use that repository.

**Comment by jgroom33** [comment]
Thanks. Yes. That's where I'm putting it now.

Is it best to then request an update to the docs that specify the available collections and their associated network os and capabilities?

If so, we can close this.

**Comment by jgroom33** [comment]
related: https://github.com/ansible/galaxy/issues/2446
