### ISSUE TITLE
Recommended settings

### ISSUE THREAD

**Issue by jgroom33** [ansible-collections/overview#92]
##### SUMMARY

It should not have taken me 12 hours to learn that this setting is required in order to successfully develop a collection

`log_messages = true`

##### ISSUE TYPE
- Bug Report

**Comment by felixfontein** [comment]
I don't know that setting, and I have been successfully developing with collections for a couple of months now. So maybe you should mention more context on this, and where you would have expected it to be documented.

**Comment by jgroom33** [comment]
using `-vvvv` during playbook executions does not:

* output the device responses
* print stack traces that occur during those executions

The above setting provides both of those

**Comment by felixfontein** [comment]
Are you talking about network modules/plugins? I saw there is a `log_messages` option in `plugins/connection/httpapi.py` in the ansible.netcommon collection. So this seems to be a very network module/plugin specific thing, and unrelated to collections at all.

**Comment by jgroom33** [comment]
Yes, the frustrations I hit were related to a network_cli collection. Agreed, it's not specifically a collection issue.

**Comment by gundalow** [comment]
@jgroom33 Thank you for raising this. I also didn't know such a setting existed
1) Did you look at any documentation when developing the collection (please list the URLs) 
2) Where do you think this should be documented 

I'd hope with a mix of 1 & 2 we can find somewhere to document this and make it more obvious. 

Could you please raise this as a Documentation bug via https://github.com/ansible/ansible/issues/new/choose
