### ISSUE TITLE
repo: community.okd

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/overview#97]
##### SUMMARY

Please create a `community.okd` collection, which will hold community OpenShift-related modules and plugins.

##### Name of collection

community.okd

##### GitHub maintainers

@geerlingguy 
@fabianvf
@Akasurde

**Comment by gundalow** [comment]
- [X] Repo
- [ ] Zuul Tenant https://github.com/ansible/project-config/pull/579
- [ ] Zuul Project https://github.com/ansible/project-config/pull/580
- [ ] Announce in Bullhorn https://github.com/ansible/community/issues/546

**Comment by geerlingguy** [comment]
@gundalow - I'm trying to get codecov set up, but when I go to https://codecov.io/gh/ansible-collections/community.okd it asks me to paste a token into my CI environment. I don't see any way for me to do that with GitHub Actions...

**Comment by gundalow** [comment]
@geerlingguy you shouldn't need a token for public repos. Have a look at Grafana or Zabbix Collections, you can just call codecov

**Comment by gundalow** [comment]
@geerlingguy Any luck with codecov? See what https://github.com/ansible-collections/community.grafana/ and https://github.com/ansible-collections/community.zabbix are doing. Otherwise feel free to shout out in `#ansible-community` on Freenode

**Comment by gundalow** [comment]
Seems like community.okd is using Molecule which doesn't currently support code coverage, so nothing we can do there,

Can this issue be closed?

**Comment by geerlingguy** [comment]
Yes, I think so.
